language: python
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install -e
  - python setup.py install
script:
  - pytest

  
matrix:
  include:
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'







