language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt
script: python tests/test_all_of_the_units.py