dist: xenial
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'

install:
- python setup.py install
- pip install Pygments collective.checkdocs
- pip install requirements.txt

script:
- python setup.py test
- python setup.py checkdocs
